2020-01-09 17:27:47,550 ERROR: Exception on /index [GET] [in /home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/routes.py", line 34, in index
    posts = current_user.folowed_posts().all()
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'folowed_posts'
2020-01-09 17:28:12,791 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
2020-01-09 17:32:02,361 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
2020-01-09 17:40:55,166 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
2020-01-10 16:56:08,706 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
2020-01-10 16:56:24,363 ERROR: Exception on / [GET] [in /home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/routes.py", line 23, in index
    posts = current_user.followed_posts().all().paginate(
AttributeError: 'list' object has no attribute 'paginate'
2020-01-10 16:58:42,330 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
2020-01-10 17:27:08,514 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
