2019-12-30 17:48:13,080 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
2020-01-07 10:24:44,586 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
2020-01-07 10:25:14,031 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
2020-01-07 12:11:57,126 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
2020-01-07 12:12:58,254 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
2020-01-07 12:13:25,033 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
2020-01-07 12:15:11,923 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
2020-01-07 12:17:18,029 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
2020-01-07 12:18:14,635 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
2020-01-07 12:18:28,642 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
2020-01-07 12:43:04,243 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
2020-01-07 12:43:19,395 ERROR: Exception on /user/sam [GET] [in /home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: followers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/routes.py", line 73, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/templates/user.html", line 11, in block "content"
    <p>{{ user.followers.count() }} followers, {{ user.followed.count() }} following.</p>
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/orm/dynamic.py", line 335, in count
    return self._clone(sess).count()
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3578, in count
    return self.from_self(col).scalar()
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3322, in scalar
    ret = self.one()
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3292, in one
    ret = self.one_or_none()
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3261, in one_or_none
    ret = list(self)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
    return self._execute_and_instances(context)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3359, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/home/samyukta/DL/my_env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: followers
[SQL: SELECT count(*) AS count_1 
FROM (SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen 
FROM user, followers 
WHERE followers.followed_id = ? AND followers.follower_id = user.id) AS anon_1]
[parameters: (2,)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2020-01-09 15:51:40,661 INFO: Microblog startup [in /home/samyukta/DS_Algo/Projects/FlaskProject/microblog/app/__init__.py:33]
